/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        cyber: {
          bg: '#0a0e1a',
          surface: '#0f1626',
          card: '#131c30',
          border: '#1e2d4a',
          'border-bright': '#2a3f5f',
          navy: '#0a1628',
          'navy-light': '#11203a',
          blue: '#1e90ff',
          'blue-bright': '#3ba7ff',
          'blue-dim': '#0a6db5',
          'blue-glow': '#1e90ff40',
          cyan: '#00e5ff',
          'cyan-bright': '#5cf5ff',
          'cyan-dim': '#00b8cc',
          'cyan-glow': '#00e5ff40',
          white: '#f0f4ff',
          'white-dim': '#c0cce0',
          text: '#e8eef8',
          'text-dim': '#8090b0',
          'text-muted': '#4a5a7a',
          red: '#ff3355',
          'red-bright': '#ff5577',
          'red-dim': '#cc2244',
          'red-glow': '#ff335540',
          green: '#00d97e',
          'green-bright': '#33e89a',
          'green-dim': '#00a862',
          'green-glow': '#00d97e40',
          warning: '#ffaa00',
          error: '#ff3355',
        },
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'scan-line': 'scanLine 2s linear infinite',
        'pulse-blue': 'pulseBlue 1.5s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
        'bounce-in': 'bounceIn 0.5s ease-out',
        'progress': 'progress 3s ease-in-out',
        'flicker': 'flicker 3s linear infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown: { '0%': { opacity: '0', transform: 'translateY(-20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(30px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        scanLine: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100vh)' } },
        pulseBlue: {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 20px #1e90ff40' },
          '50%': { opacity: '0.7', boxShadow: '0 0 40px #1e90ff80' },
        },
        glow: {
          '0%, 100%': { textShadow: '0 0 10px #00e5ff80' },
          '50%': { textShadow: '0 0 25px #00e5ffff, 0 0 10px #00e5ff80' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.8)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        progress: { '0%': { width: '0%' }, '100%': { width: '100%' } },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '48%': { opacity: '1' },
          '49%': { opacity: '0.4' },
          '50%': { opacity: '1' },
          '52%': { opacity: '0.7' },
          '53%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
